# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 259cb9c141fda29779901e57f41ffedbcb12473bc5712e3871ddf951ef1166c90f0207ea2b5cbdf7c8c53cf1e962332f304589cd081cd883b20c039c152fab0f

test:
  secret_key_base: 2604ce716a2cea605ac46179e689ca7fcbe21f6519249e167235aef3b20bece38965af170f8d6371c1b0aa55872777b19c4cb8552049ac9b6a7b29f59b108a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
